<a href="https://colab.research.google.com/github/LucasCod-eng/Deep-Learning/blob/main/Deep_Learning_A_Z_Classifica%C3%A7%C3%A3o_bin%C3%A1ria_Breast_Cancer_Simples.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
pd.__version__

'2.2.2'

In [ ]:
# previsores
X = pd.read_csv('entradas_breast.csv')
X

radius_mean   texture_mean   perimeter_mean   area_mean  \
0           17.99          10.38           122.80      1001.0   
1           20.57          17.77           132.90      1326.0   
2           19.69          21.25           130.00      1203.0   
3           11.42          20.38            77.58       386.1   
4           20.29          14.34           135.10      1297.0   
..            ...            ...              ...         ...   
564         21.56          22.39           142.00      1479.0   
565         20.13          28.25           131.20      1261.0   
566         16.60          28.08           108.30       858.1   
567         20.60          29.33           140.10      1265.0   
568          7.76          24.54            47.92       181.0   

      smoothness_mean   compactness_mean   concavity_mean  \
0             0.11840            0.27760          0.30010   
1             0.08474            0.07864          0.08690   
2             0.10960            0.15990          0.19740   
3             0.14250            0.28390          0.24140   
4             0.10030            0.13280        198.00000   
..                ...                ...              ...   
564         111.00000            0.11590          0.24390   
565           0.09780            0.10340        144.00000   
566           0.08455            0.10230          0.09251   
567           0.11780          277.00000          0.35140   
568           0.05263            0.04362          0.00000   

     concave_points_mean   symmetry_mean   fractal_dimension_mean  ...  \
0                0.14710          0.2419                  0.07871  ...   
1                0.07017          0.1812                  0.05667  ...   
2                0.12790          0.2069                  0.05999  ...   
3                0.10520          0.2597                  0.09744  ...   
4                0.10430          0.1809                  0.05883  ...   
..                   ...             ...                      ...  ...   
564              0.13890          0.1726                  0.05623  ...   
565              0.09791          0.1752                  0.05533  ...   
566              0.05302        159.0000                  0.05648  ...   
567            152.00000          0.2397                  0.07016  ...   
568              0.00000          0.1587                  0.05884  ...   

      radius_worst   texture_worst   perimeter_worst   area_worst  \
0            25.38           17.33            184.60       2019.0   
1            24.99           23.41            158.80       1956.0   
2            23.57           25.53            152.50       1709.0   
3            14.91           26.50             98.87        567.7   
4            22.54           16.67            152.20       1575.0   
..             ...             ...               ...          ...   
564          25.45           26.40            166.10       2027.0   
565          23.69           38.25            155.00       1731.0   
566          18.98           34.12            126.70       1124.0   
567          25.74           39.42            184.60       1821.0   
568        9456.00           30.37             59.16        268.6   

      smoothness_worst   compactness_worst   concavity_worst  \
0              0.16220             0.66560            0.7119   
1              0.12380             0.18660            0.2416   
2              0.14440             0.42450            0.4504   
3              0.20980             0.86630            0.6869   
4              0.13740           205.00000            0.4000   
..                 ...                 ...               ...   
564          141.00000             0.21130            0.4107   
565            0.11660             0.19220            0.3215   
566            0.11390             0.30940            0.3403   
567          165.00000             0.86810            0.9387   
568            0.08996             0.06444            0.0000   

     

In [ ]:
# classe
y = pd.read_csv('saidas_breast.csv')
y

0
0    0
1    0
2    0
3    0
4    0
..  ..
564  0
565  0
566  0
567  0
568  1

[569 rows x 1 columns]

In [ ]:
import sklearn
from sklearn.model_selection import train_test_split

In [ ]:
sklearn.__version__

'1.6.1'

In [ ]:
X_treinamento, X_teste, y_treinamento, y_teste = train_test_split(X, y, test_size=0.25)

In [ ]:
X_treinamento.shape, y_treinamento.shape

((426, 30), (426, 1))

In [ ]:
X_teste.shape,y_teste.shape

((143, 30), (143, 1))

In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Sequential


In [ ]:
rede_neural = Sequential([
    tf.keras.layers.Input(shape=(30,)),
    tf.keras.layers.Dense(units=16, activation='relu', kernel_initializer='random_uniform'),
    tf.keras.layers.Dense(units=16, activation='relu', kernel_initializer='random_uniform'),
    tf.keras.layers.Dense(units=1, activation='sigmoid'),

])

In [ ]:
rede_neural.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_2 (Dense)                      │ (None, 16)                  │             496 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ (None, 16)                  │             272 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_4 (Dense)                      │ (None, 1)                   │              17 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 785 (3.07 KB)

 Trainable params: 785 (3.07 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
otimizador = tf.keras.optimizers.Adam(learning_rate=0.001, decay=0.0001, clipvalue=0.5)

In [ ]:
rede_neural.compile(optimizer='adam', loss='binary_crossentropy', metrics=['binary_accuracy'])

In [ ]:
rede_neural.fit(X_treinamento, y_treinamento, batch_size = 10, epochs = 100)

Epoch 1/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - binary_accuracy: 0.5447 - loss: 1.1214
Epoch 2/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - binary_accuracy: 0.6416 - loss: 0.7759
Epoch 3/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - binary_accuracy: 0.7143 - loss: 0.5198
Epoch 4/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - binary_accuracy: 0.7714 - loss: 0.4507
Epoch 5/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - binary_accuracy: 0.7860 - loss: 0.4461
Epoch 6/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - binary_accuracy: 0.8385 - loss: 0.4104
Epoch 7/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - binary_accuracy: 0.8786 - loss: 0.3116
Epoch 8/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - binary_accuracy: 0.9031 - loss: 0.3061
Epoch 9/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - binary_accuracy: 0.8888 - loss: 0.2836
Epoch 10/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - binary_accuracy: 0.8587 - loss: 0.3486
Epoch 11/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.8723 -

In [ ]:
pessos0 = rede_neural.layers[0].get_weights()
pessos0

[array([[-8.04837197e-02,  6.24520145e-02, -1.95808560e-01,
         -1.44015417e-01, -1.72234687e-03,  3.04641604e-01,
         -2.93149650e-02,  1.20793208e-01, -4.63224836e-02,
         -1.31468670e-02,  7.76405539e-03, -2.59006798e-01,
         -1.81928668e-02, -2.11118504e-01,  3.95269096e-02,
          3.84213589e-02],
        [-2.14586258e-01, -1.32898032e-03, -1.19375251e-01,
          4.09178361e-02,  8.87818709e-02,  8.39970857e-02,
          1.88285522e-02,  8.13174397e-02, -4.23736684e-02,
          6.15655743e-02,  7.21427649e-02,  1.27065733e-01,
         -1.01594776e-02,  1.02602713e-01,  8.56559724e-02,
          9.40161496e-02],
        [-5.66689298e-02,  1.63493916e-01, -1.02750175e-01,
         -2.61906028e-01, -1.12151928e-01,  3.01916301e-01,
          3.81753482e-02,  2.28973940e-01, -4.05613035e-02,
         -2.19676420e-01,  2.07461059e-01, -1.91867828e-01,
         -1.15342829e-02, -1.00652322e-01,  1.16531998e-01,
          1.61097512e-01],
        [ 5.4013997

In [ ]:
len(pessos0)

2

In [ ]:
pessos0[0]

array([[-8.04837197e-02,  6.24520145e-02, -1.95808560e-01,
        -1.44015417e-01, -1.72234687e-03,  3.04641604e-01,
        -2.93149650e-02,  1.20793208e-01, -4.63224836e-02,
        -1.31468670e-02,  7.76405539e-03, -2.59006798e-01,
        -1.81928668e-02, -2.11118504e-01,  3.95269096e-02,
         3.84213589e-02],
       [-2.14586258e-01, -1.32898032e-03, -1.19375251e-01,
         4.09178361e-02,  8.87818709e-02,  8.39970857e-02,
         1.88285522e-02,  8.13174397e-02, -4.23736684e-02,
         6.15655743e-02,  7.21427649e-02,  1.27065733e-01,
        -1.01594776e-02,  1.02602713e-01,  8.56559724e-02,
         9.40161496e-02],
       [-5.66689298e-02,  1.63493916e-01, -1.02750175e-01,
        -2.61906028e-01, -1.12151928e-01,  3.01916301e-01,
         3.81753482e-02,  2.28973940e-01, -4.05613035e-02,
        -2.19676420e-01,  2.07461059e-01, -1.91867828e-01,
        -1.15342829e-02, -1.00652322e-01,  1.16531998e-01,
         1.61097512e-01],
       [ 5.40139973e-02, -2.24753693e

In [ ]:
previsoes = rede_neural.predict(X_teste)
previsoes = (previsoes > 0.5)
previsoes

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step 


array([[ True],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [

In [ ]:
y_teste

0
91   0
284  1
498  0
378  1
346  1
..  ..
299  1
308  1
243  1
262  0
351  0

[143 rows x 1 columns]

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [ ]:
accuracy_score(y_teste, previsoes)

0.8951048951048951

In [ ]:
confusion_matrix(y_teste, previsoes)

array([[43,  6],
       [ 9, 85]])

In [ ]:
rede_neural.evaluate(X_teste, y_teste)

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - binary_accuracy: 0.9090 - loss: 0.3022 


[0.39891448616981506, 0.8951048851013184]