<a href="https://colab.research.google.com/github/LucasCod-eng/Deep-Learning/blob/main/Deep_Learning_A_Z_Boltzmann_Machines_Recomenda%C3%A7%C3%B5es.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np


In [3]:
np.__version__

'1.26.4'

In [5]:
import rbm

In [6]:
rbm = rbm.RBM(num_visible = 6, num_hidden= 2)

In [8]:
base = np.array([[1, 1, 1, 0, 0, 0],
                [1, 0, 1, 0, 0, 0],
                [1, 1, 1, 0, 0, 0],
                [0, 0, 1, 1, 1, 1],
                [0, 0, 1, 1, 0, 1],
                [0, 0, 1, 1, 0, 1]])

In [9]:
base.shape

(6, 6)

In [10]:
filmes = ["A bruxa", "Invocação do mal", "O chamado", "Se beber não case", "Gente Grande", "American Pie"]

In [14]:
rbm.train(base, max_epochs=5000)

Epoch 0: error is 0.6715257495381668
Epoch 1: error is 0.6715232652224291
Epoch 2: error is 0.6715207844441206
Epoch 3: error is 0.6715183071865294
Epoch 4: error is 0.6715158334330605
Epoch 5: error is 0.6715133631672351
Epoch 6: error is 0.6715108963726881
Epoch 7: error is 0.6715084330331696
Epoch 8: error is 0.6715059731325419
Epoch 9: error is 0.6715035166547805
Epoch 10: error is 0.6715010635839714
Epoch 11: error is 0.6714986139043119
Epoch 12: error is 1.6223600005704635
Epoch 13: error is 0.6715163244257982
Epoch 14: error is 1.6210614290766583
Epoch 15: error is 0.6715413585156161
Epoch 16: error is 0.6715385905056752
Epoch 17: error is 0.671535827901148
Epoch 18: error is 0.6715330706781182
Epoch 19: error is 0.671530318812719
Epoch 20: error is 0.671527572281133
Epoch 21: error is 0.671524831059596
Epoch 22: error is 0.6715220951243973
Epoch 23: error is 0.6715193644518808
Epoch 24: error is 0.6715166390184484
Epoch 25: error is 0.671513918800559
Epoch 26: error is 0.671511

In [15]:
rbm.weights, rbm.weights.shape

(array([[ 2.76054951,  2.997901  ,  0.39569327],
        [-1.49598208, -3.53520315,  9.47393325],
        [ 0.68008049, -8.94108631,  3.75711701],
        [ 5.39835212,  4.60030051,  2.03177343],
        [ 1.24608806,  4.05255218, -9.71321785],
        [-1.4838881 ,  0.78466774, -5.1796811 ],
        [ 1.25116355,  4.04812648, -9.71461972]]),
 (7, 3))

In [18]:
usuario1 = np.array([[1,1,0,1,0,0]])
usuario2 = np.array([[0,0,0,1,1,0]])

In [19]:
rbm.run_visible(usuario1)

array([[0., 1.]])

In [20]:
rbm.run_visible(usuario2)

array([[1., 0.]])

In [23]:
camada_escondida = np.array([[0, 1]])
recomendacao = rbm.run_hidden(camada_escondida)
recomendacao

array([[1., 1., 1., 0., 0., 0.]])

In [25]:
for i in range(len(usuario1[0])):
  if usuario1[0, i] == 0 and recomendacao[0, i] == 1:
    print(filmes[i])

O chamado
